version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alwaysfit-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=alwaysfit
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - alwaysfit-network

  db:
    image: mysql:8.0
    container_name: alwaysfit-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: alwaysfit
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - alwaysfit-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: alwaysfit-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - alwaysfit-network

volumes:
  db_data:

networks:
  alwaysfit-network:
    driver: bridge
